name: Deploy FastAPI + Nginx to Azure App Service

on:
  push:
    branches:
      - main

env:
  WEBAPP_NAME: fastapi-nginx-app
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push FastAPI Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest -f fastapi/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/nginx-proxy:latest -f nginx/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/nginx-proxy:latest

      - name: Create Azure App Service Plan (If Not Exists)
        run: |
          az appservice plan create --name hngAppPlan \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --sku B1 --is-linux || true

      - name: Deploy FastAPI App Service
        run: |
          az webapp create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --plan hngAppPlan \
            --name $WEBAPP_NAME-fastapi \
            --deployment-container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest

      - name: Deploy Nginx App Service
        run: |
          az webapp create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --plan hngAppPlan \
            --name $WEBAPP_NAME-nginx \
            --deployment-container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/nginx-proxy:latest

      - name: Verify Deployment
        run: |
          az webapp show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name $WEBAPP_NAME-nginx --query "defaultHostName" -o tsv
