name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name hngregistry

      - name: Build and Push FastAPI Image
        run: |
          docker build -t hngregistry.azurecr.io/fastapi-app:latest .
          docker push hngregistry.azurecr.io/fastapi-app:latest
      - name: Build and Push Nginx Image
        run: |
          docker build -t hngregistry.azurecr.io/fastapi-nginx:latest -f Dockerfile.nginx .
          docker push hngregistry.azurecr.io/fastapi-nginx:latest

      - name: Deploy Nginx to ACI
        run: |
          # Delete previous container if exists (optional)
          az container delete --name nginx-container --resource-group az-StorageRg --yes || true
          az container create --resource-group az-StorageRg --name nginx-container \
            --image hngregistry.azurecr.io/fastapi-nginx:latest \
            --cpu 1 --memory 1 \
            --registry-login-server hngregistry.azurecr.io \
            --registry-username $(az acr credential show --name hngregistry --query "username" -o tsv) \
            --registry-password $(az acr credential show --name hngregistry --query "passwords[0].value" -o tsv) \
            --dns-name-label mynginxproxy1234 --ports 80 \
            --os-type Linux
      - name: Deploy to Azure Container Instances
        run: | 
         # Delete previous container if exists (optional)
         az container delete --name fastapi-container --resource-group az-StorageRg --yes || true
         az container create --resource-group az-StorageRg \
          --name fastapi-container \
          --image hngregistry.azurecr.io/fastapi-app:latest \
          --cpu 1 --memory 1 \
          --registry-login-server hngregistry.azurecr.io \
          --registry-username $(az acr credential show --name hngregistry --query "username" -o tsv) \
          --registry-password $(az acr credential show --name hngregistry --query "passwords[0].value" -o tsv) \
          --dns-name-label fastapi-app \
          --ports 8000 \
          --os-type Linux \
          --restart-policy Always
    